/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts.poppy.rahayu;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO THINKPAD X260
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        popi_username = new javax.swing.JTextField();
        popi_password = new javax.swing.JPasswordField();
        popi_login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("         APLIKASI KELAS SISTEM INFORMASI  22");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 420, 70);
        jPanel1.add(popi_username);
        popi_username.setBounds(180, 130, 109, 22);

        popi_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(popi_password);
        popi_password.setBounds(180, 180, 109, 22);

        popi_login.setText("LOGIN");
        popi_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_loginActionPerformed(evt);
            }
        });
        jPanel1.add(popi_login);
        popi_login.setBounds(200, 230, 70, 20);

        jLabel3.setBackground(new java.awt.Color(255, 204, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Forgot Password?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 210, 130, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO THINKPAD X260\\Documents\\NetBeansProjects\\UAS-POPPY RAHAYU\\src\\uts\\poppy\\rahayu\\login.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popi_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_loginActionPerformed
        // TODO add your handling code here:
        String username="Bendahara";
        String password="sisteminformasi22";
        if(username.equalsIgnoreCase(popi_username.getText())&&
            password.equalsIgnoreCase(popi_password.getText())){
            this.setVisible(false);
            new MenuUtama().setVisible(true);
            javax.swing.JOptionPane.showMessageDialog(null,"ANDA BERHASIL LOGIN");
            dispose();
        }else{
            javax.swing.JOptionPane.showMessageDialog(null,"MAAF USER DAN PASSWORD ANDA SALAH","Error", JOptionPane.ERROR_MESSAGE);
            popi_username.setText("Username");
            popi_password.setText("password");
            popi_username.requestFocus();
        }
    }//GEN-LAST:event_popi_loginActionPerformed

    private void popi_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popi_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton popi_login;
    private javax.swing.JPasswordField popi_password;
    private javax.swing.JTextField popi_username;
    // End of variables declaration//GEN-END:variables
}
