/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts.poppy.rahayu;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.awt.event.KeyEvent;
import java.sql.Date;
/**
 *
 * @author LENOVO THINKPAD X260
 */
public class UangKas extends javax.swing.JFrame {
private Connection con;
    private Statement stat;
    private ResultSet res;
    private String t, keterangan;
    private DefaultTableModel dtm;
    /**
     * Creates new form UangKas
     */
    public UangKas() {
        initComponents();
        setTitle("LAPORAN UANGKAS");
        koneksi ();
        kosongkan ();
        tabel ();
        //rata kiri dan kanan
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
           (screenSize.width - frameSize.width) / 3,
           (screenSize.height - frameSize.height) /4);
    }

    
    private void koneksi (){
     try {
         Class.forName("com.mysql.cj.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/aplikasikelas", "root", "");
         stat=con.createStatement();
         } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);}   
    }
    
    
    private void kosongkan(){
     popi_no.setText("");
     popi_tanggal.setDate(null);
     popi_nama.setText("");
     popi_keterangan.setText("");
     pembayaran.setText("");
     pengeluaran.setText("");
     popi_saldoakhir.setText("");
     pembayaran.setVisible(false);
     pengeluaran.setVisible(false);
     popi_no.requestFocus();
    }
    
    
    private void tabel (){
        DefaultTableModel t= new DefaultTableModel();
        t.addColumn("No");
        t.addColumn("Tanggal");
        t.addColumn("Nama");
        t.addColumn("Pemasukan");
        t.addColumn("Pengeluaran");
        t.addColumn("SaldoAkhir");
        t.addColumn("Keterangan");
        popi_table.setModel(t); try{ res= stat.executeQuery("select * from uangkas");
    while (res.next()) {
    t.addRow(new Object[]{ 
      res.getString("No"),
      res.getString("Tanggal"),
      res.getString("Nama"),
      res.getString("Pemasukan"),
      res.getString("Pengeluaran"),
      res.getString("SaldoAkhir"),
      res.getString("Keterangan")
        });}
}catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);}    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        popi_menu = new javax.swing.JButton();
        popi_no = new javax.swing.JTextField();
        popi_tanggal = new com.toedter.calendar.JDateChooser();
        popi_lihat = new javax.swing.JButton();
        popi_edit = new javax.swing.JButton();
        popi_simpan = new javax.swing.JButton();
        popi_clear = new javax.swing.JButton();
        popi_hapus = new javax.swing.JButton();
        popi_search = new javax.swing.JButton();
        popi_nama = new javax.swing.JTextField();
        popi_saldoakhir = new javax.swing.JTextField();
        UANGKAS = new javax.swing.JTextField();
        popi_uangkas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        popi_table = new javax.swing.JTable();
        popi_keterangan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        popi_pembayaran = new javax.swing.JTextField();
        popi_pengeluaran = new javax.swing.JTextField();
        pembayaran = new javax.swing.JCheckBox();
        pengeluaran = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("LAPORAN KEUANGAN KAS KELAS");

        popi_menu.setText("MENU");
        popi_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_menuActionPerformed(evt);
            }
        });

        popi_no.setText("NO");
        popi_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_noActionPerformed(evt);
            }
        });
        popi_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                popi_noKeyTyped(evt);
            }
        });

        popi_lihat.setText("Lihat");
        popi_lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_lihatActionPerformed(evt);
            }
        });

        popi_edit.setText("EDIT");
        popi_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_editActionPerformed(evt);
            }
        });

        popi_simpan.setText("SIMPAN");
        popi_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_simpanActionPerformed(evt);
            }
        });

        popi_clear.setText("CLEAR");
        popi_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_clearActionPerformed(evt);
            }
        });

        popi_hapus.setText("HAPUS");
        popi_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_hapusActionPerformed(evt);
            }
        });

        popi_search.setText("SEARCH");
        popi_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_searchActionPerformed(evt);
            }
        });

        popi_nama.setText("Nama");

        popi_saldoakhir.setText("SALDO AKHIR");
        popi_saldoakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_saldoakhirActionPerformed(evt);
            }
        });
        popi_saldoakhir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                popi_saldoakhirKeyTyped(evt);
            }
        });

        UANGKAS.setText("UANGKAS/2MINGGU");

        popi_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        popi_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popi_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(popi_table);

        popi_keterangan.setText("KETERANGAN");

        jLabel3.setText("NO");

        jLabel4.setText("TANGGAL");

        jLabel5.setText("NAMA");

        jLabel6.setText("KETERANGAN");

        jLabel7.setText("SALDO AKHIR");

        jLabel8.setText("Rp.");

        jLabel9.setText("Rp.");

        popi_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_pembayaranActionPerformed(evt);
            }
        });
        popi_pembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                popi_pembayaranKeyTyped(evt);
            }
        });

        popi_pengeluaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                popi_pengeluaranKeyTyped(evt);
            }
        });

        pembayaran.setText("Pembayaran");
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });
        pembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pembayaranKeyTyped(evt);
            }
        });

        pengeluaran.setText("Pengeluaran");
        pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengeluaranActionPerformed(evt);
            }
        });
        pengeluaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pengeluaranKeyTyped(evt);
            }
        });

        jLabel10.setText("Pembayaran");

        jLabel11.setText("Pengeluaran");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(popi_edit)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(popi_menu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(popi_simpan)
                        .addGap(64, 64, 64)
                        .addComponent(popi_clear)
                        .addGap(83, 83, 83)
                        .addComponent(popi_hapus)
                        .addGap(91, 91, 91)
                        .addComponent(popi_search)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(167, 167, 167)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(195, 195, 195)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pengeluaran)
                                            .addComponent(pembayaran))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(popi_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(popi_no, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(UANGKAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(popi_uangkas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(popi_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(popi_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(popi_lihat))
                                            .addComponent(popi_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(108, 108, 108)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel9))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(popi_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(popi_saldoakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(72, 72, 72)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(popi_menu)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pembayaran)
                                    .addComponent(jLabel8)
                                    .addComponent(popi_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(popi_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pengeluaran)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(popi_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(popi_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(popi_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(popi_lihat)
                                    .addComponent(jLabel5))))
                        .addGap(14, 14, 14)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(popi_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(popi_saldoakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UANGKAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(popi_uangkas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popi_clear)
                    .addComponent(popi_simpan)
                    .addComponent(popi_edit)
                    .addComponent(popi_hapus)
                    .addComponent(popi_search))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popi_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_simpanActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(tampilan);
        String Tanggal=String.valueOf(fm.format(popi_tanggal.getDate()));
        
        try {
         stat.executeUpdate("insert into uangkas values ("
             + "'" + popi_no.getText()+"',"
             + "'" + Tanggal+"',"
             + "'" + popi_nama.getText()+"',"
             + "'" + pembayaran.getText()+"',"
             + "'" + pengeluaran.getText()+"',"
             + "'" + popi_saldoakhir.getText()+"',"
             + "'" + popi_keterangan.getText()+"')");
         kosongkan();
         JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
         new UangKas().setVisible(true);
         dispose();
         } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Gagal Menyimpan Data! : "+e);
        }
    }//GEN-LAST:event_popi_simpanActionPerformed

    private void popi_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_hapusActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin menghapus data?","Confirmation",
                JOptionPane.YES_NO_OPTION);
         try{
             String sql="delete from uangkas where No='"+popi_no.getText()+"'";
             PreparedStatement st=con.prepareStatement (sql);
             st.executeUpdate();
             kosongkan();
             JOptionPane.showMessageDialog(null, "Delete Data Sukses");
             new UangKas().setVisible(true);
             dispose();
         } catch (Exception e)
         {
             JOptionPane.showMessageDialog(null, "Delete Data Gagal");
         }
    }//GEN-LAST:event_popi_hapusActionPerformed

    private void popi_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_editActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin mengedit data?","Confirmation",
                JOptionPane.YES_NO_OPTION);
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(tampilan);
        String Tanggal=String.valueOf(fm.format(popi_tanggal.getDate()));
    try{
    String sql = "update uangkas set No=?,Tanggal=?,Nama=?,Pemasukan=?,Pengeluaran=?,"
            + "SaldoAkhir=?,Keterangan=? where No='"
                    + popi_no.getText()+"'";
    PreparedStatement st=con.prepareStatement(sql);
    if(ok==0){
    try{
    st.setString(1,popi_no.getText());
    st.setString(2,Tanggal);
    st.setString(3,popi_nama.getText());
    st.setString(4,pembayaran.getText());
    st.setString(5,popi_uangkas.getText());
    st.setString(6,popi_saldoakhir.getText());
    st.setString(7,popi_keterangan.getText());
    st.executeUpdate();
    kosongkan();
    JOptionPane.showMessageDialog(null,"Edit Data Sukses");
    new UangKas().setVisible(true);
    dispose();
    }catch (Exception e){
    JOptionPane.showMessageDialog(null, "Edit Data Gagal");}}
    }catch (Exception e){}
    }//GEN-LAST:event_popi_editActionPerformed

    private void popi_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_clearActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_popi_clearActionPerformed

    private void popi_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_searchActionPerformed
        // TODO add your handling code here:
        try {
    res=stat.executeQuery("select * from uangkas where "+ "No='" +popi_no.getText()
    +"'" ); while (res.next())
    { popi_tanggal.setDate(res.getDate("Tanggal"));
      popi_nama.setText(res.getString("Nama"));
      pembayaran.setText(res.getString("Pemasukan"));
      pengeluaran.setText(res.getString("Pengeluaran"));
      popi_saldoakhir.setText(res.getString("SaldoAkhir"));
      popi_keterangan.setText(res.getString("Keterangan"));
    }
}catch (Exception e) {
JOptionPane.showMessageDialog(rootPane, e);
}
    }//GEN-LAST:event_popi_searchActionPerformed

    private void popi_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_menuActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_popi_menuActionPerformed

    private void popi_lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_lihatActionPerformed
        // TODO add your handling code here:
        new TableMahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_popi_lihatActionPerformed

    private void popi_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popi_tableMouseClicked
        // TODO add your handling code here:
         int i = popi_table.getSelectedRow();
    if(i==-1){
    return;
    }
    String code = (String)popi_table.getValueAt(i,0);
    String code1 = (String)popi_table.getValueAt(i,1);
    String code2 = (String)popi_table.getValueAt(i,2);
    String code3 = (String)popi_table.getValueAt(i,3);
    String code4 = (String)popi_table.getValueAt(i,4);
    String code5 = (String)popi_table.getValueAt(i,5);
    String code6 = (String)popi_table.getValueAt(i,6);
    
    popi_no.setText(code);
    popi_tanggal.setDateFormatString(code1);
    popi_nama.setText(code2);
    pembayaran.setText(code3);
    pengeluaran.setText(code4);
    popi_saldoakhir.setText(code5);
    popi_keterangan.setText(code6);
    }//GEN-LAST:event_popi_tableMouseClicked

    private void popi_saldoakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_saldoakhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popi_saldoakhirActionPerformed

    private void popi_saldoakhirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_popi_saldoakhirKeyTyped
        // TODO add your handling code here:
        char popi=evt.getKeyChar();
        if(!(Character.isDigit(popi)));
        {
            evt.consume();
        }
    }//GEN-LAST:event_popi_saldoakhirKeyTyped

    private void popi_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_popi_noKeyTyped
        // TODO add your handling code here:
        char popi=evt.getKeyChar();
        if(!(Character.isDigit(popi)));
        {
            evt.consume();
        }
    }//GEN-LAST:event_popi_noKeyTyped

    private void popi_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popi_noActionPerformed

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
        keterangan="Uang Masuk";
        pengeluaran.setSelected(false);
        popi_keterangan.setText(""+keterangan);
    }//GEN-LAST:event_pembayaranActionPerformed

    private void pembayaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pembayaranKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pembayaranKeyTyped

    private void pengeluaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pengeluaranKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pengeluaranKeyTyped

    private void popi_pembayaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_popi_pembayaranKeyTyped
        // TODO add your handling code here:
        char popi=evt.getKeyChar();
        if(!(Character.isDigit(popi)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_popi_pembayaranKeyTyped

    private void popi_pengeluaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_popi_pengeluaranKeyTyped
        // TODO add your handling code here:
        char popi=evt.getKeyChar();
        if(!(Character.isDigit(popi)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_popi_pengeluaranKeyTyped

    private void pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengeluaranActionPerformed
        // TODO add your handling code here:
        keterangan="Uang Keluar";
        pembayaran.setSelected(false);
        popi_keterangan.setText(""+keterangan);
    }//GEN-LAST:event_pengeluaranActionPerformed

    private void popi_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_pembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popi_pembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UangKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UangKas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UANGKAS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox pembayaran;
    private javax.swing.JCheckBox pengeluaran;
    private javax.swing.JButton popi_clear;
    private javax.swing.JButton popi_edit;
    private javax.swing.JButton popi_hapus;
    private javax.swing.JTextField popi_keterangan;
    private javax.swing.JButton popi_lihat;
    private javax.swing.JButton popi_menu;
    public javax.swing.JTextField popi_nama;
    private javax.swing.JTextField popi_no;
    private javax.swing.JTextField popi_pembayaran;
    private javax.swing.JTextField popi_pengeluaran;
    private javax.swing.JTextField popi_saldoakhir;
    private javax.swing.JButton popi_search;
    private javax.swing.JButton popi_simpan;
    private javax.swing.JTable popi_table;
    private com.toedter.calendar.JDateChooser popi_tanggal;
    private javax.swing.JTextField popi_uangkas;
    // End of variables declaration//GEN-END:variables
}
