/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts.poppy.rahayu;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO THINKPAD X260
 */
public class Mahasiswa extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;

    /**
     * Creates new form Mahasiswa
     */
    public Mahasiswa() {
    initComponents();
    setTitle("FORM MAHASISWA");
    koneksi();
    kosongkan();
}

private void koneksi() {
    try {
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/aplikasikelas", "root", "");
        stat = con.createStatement();
    } catch (Exception e) {
       JOptionPane.showMessageDialog(null, stat);
    }
}

private void kosongkan() {
    popi_nim.setText("");
    popi_nama.setText("");
    popi_jk.setSelectedIndex(-1);
    popi_nohp.setText("");
    popi_alamat.setText("");
    popi_nim.requestFocus();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        popi_edit = new javax.swing.JButton();
        popi_hapus = new javax.swing.JButton();
        popi_simpan = new javax.swing.JButton();
        popi_search = new javax.swing.JButton();
        popi_nim = new javax.swing.JTextField();
        popi_nama = new javax.swing.JTextField();
        popi_jk = new javax.swing.JComboBox<>();
        popi_nohp = new javax.swing.JTextField();
        popi_alamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JLabel = new javax.swing.JLabel();
        popi_lihat = new javax.swing.JButton();
        popi_menu = new javax.swing.JButton();

        jTextField6.setText("jTextField6");

        jTextField3.setText("jTextField3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(452, 452));

        jPanel1.setLayout(null);

        popi_edit.setText("EDIT");
        popi_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_editActionPerformed(evt);
            }
        });

        popi_hapus.setText("HAPUS");
        popi_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_hapusActionPerformed(evt);
            }
        });

        popi_simpan.setText("SIMPAN");
        popi_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_simpanActionPerformed(evt);
            }
        });

        popi_search.setText("SEARCH");
        popi_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_searchActionPerformed(evt);
            }
        });

        popi_nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_nimActionPerformed(evt);
            }
        });
        popi_nim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                popi_nimKeyTyped(evt);
            }
        });

        popi_jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        popi_jk.setSelectedIndex(-1);
        popi_jk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_jkActionPerformed(evt);
            }
        });

        popi_nohp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                popi_nohpKeyTyped(evt);
            }
        });

        jLabel8.setText("NIM");

        jLabel9.setText("NAMA");

        jLabel10.setText("Jenis Kelamin");

        jLabel11.setText("No Handphone");

        jLabel12.setText("Alamat");

        JLabel.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        JLabel.setForeground(new java.awt.Color(255, 204, 0));
        JLabel.setText("DATA MAHASISWA");

        popi_lihat.setText("LIHAT");
        popi_lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_lihatActionPerformed(evt);
            }
        });

        popi_menu.setText("MENU");
        popi_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(popi_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(popi_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(popi_jk, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(popi_alamat))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(popi_nohp)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(popi_edit)
                        .addGap(53, 53, 53)
                        .addComponent(popi_hapus)
                        .addGap(57, 57, 57)
                        .addComponent(popi_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(popi_search)
                        .addGap(50, 50, 50)
                        .addComponent(popi_lihat))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(537, Short.MAX_VALUE)
                        .addComponent(popi_menu)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(popi_menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popi_nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popi_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popi_jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popi_nohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popi_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popi_simpan)
                    .addComponent(popi_hapus)
                    .addComponent(popi_edit)
                    .addComponent(popi_search)
                    .addComponent(popi_lihat))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popi_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_menuActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_popi_menuActionPerformed

    private void popi_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_editActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null, "Apakah yakin ingin mengedit data?","Confirmation",JOptionPane.YES_NO_OPTION);
        try{
            String sql="update mahasiswa set Nim=?,Nama=?,JenisKelamin=?,NoHp=?,Alamat=?where Nim='"+popi_nim.getText()+"'";
            PreparedStatement st=con.prepareStatement(sql);
            if(ok==0)
            {
            try{
            st.setString(1,popi_nim.getText());
            st.setString(2, popi_nama.getText());
            st.setString(3,(String)popi_jk.getSelectedItem());
            st.setString(4,popi_nohp.getText());
            st.setString(5,popi_alamat.getText());
            st.executeUpdate();
            kosongkan();
            JOptionPane.showMessageDialog(null,"Edit Data Sukses");
            new Mahasiswa().setVisible(true);
            dispose();
            }catch (Exception e)
            {
            JOptionPane.showMessageDialog(null,"Edit Data Gagal");
            }
            }
            }catch (Exception e){
        }
    }//GEN-LAST:event_popi_editActionPerformed

    private void popi_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_nimActionPerformed
        // TODO add your handling code here:
        try{
            res=stat.executeQuery("select * from mahasiswa where"+"Nim='"+
                    popi_nim.getText()
                    +"'");while(res.next())
            {popi_nama.setText(res.getString("Nama"));
            popi_jk.setSelectedItem(res.getString("JenisKelamin"));
            popi_nohp.setText(res.getString("NoHp"));
            popi_alamat.setText(res.getString("Alamat"));
            }
        }catch (Exception e){
          JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_popi_nimActionPerformed

    private void popi_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_simpanActionPerformed
        // TODO add your handling code here:
        try{
            stat.executeUpdate("insert into mahasiswa values("
            +"'"+popi_nim.getText()+"',"
            +"'"+popi_nama.getText()+"',"
            +"'"+popi_jk.getSelectedItem()+"',"
            +"'"+popi_nohp.getText()+"',"
            +"'"+popi_alamat.getText()+"')");
            kosongkan();
            JOptionPane.showMessageDialog(null,"Berhasil Menyimpan Data");
            new Mahasiswa().setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Gagal Menyimpan Data!:"+e);
        }
    }//GEN-LAST:event_popi_simpanActionPerformed

    private void popi_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_hapusActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin menghapus?","Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok==0)
        {
        try{
            String sql="delete from mahasiswa where Nim='"+popi_nim.getText()+"'";
            PreparedStatement st=con.prepareStatement(sql);
            st.executeUpdate();
            kosongkan();
            JOptionPane.showMessageDialog(null,"Delete Data Sukses");
            new Mahasiswa().setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Delete Data Gagal");
        }
        }
    }//GEN-LAST:event_popi_hapusActionPerformed

    private void popi_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_searchActionPerformed
        // TODO add your handling code here:
        try{
            res=stat.executeQuery("select * from mahasiswa where"+"Nim='"+popi_nim.getText()+"'");
            while(res.next())
            {popi_nama.setText(res.getString("Nama"));
            popi_jk.setSelectedItem(res.getString("JenisKelamin"));
            popi_nohp.setText(res.getString("NoHp"));
            popi_alamat.setText(res.getString("Alamat"));
        }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_popi_searchActionPerformed

    private void popi_lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_lihatActionPerformed
        // TODO add your handling code here:
        new TableMahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_popi_lihatActionPerformed

    private void popi_jkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_jkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popi_jkActionPerformed

    private void popi_nimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_popi_nimKeyTyped
        // TODO add your handling code here:
        char popi=evt.getKeyChar();
        if(!(Character.isDigit(popi)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_popi_nimKeyTyped

    private void popi_nohpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_popi_nohpKeyTyped
        // TODO add your handling code here:
        char popi=evt.getKeyChar();
        if(!(Character.isDigit(popi)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_popi_nohpKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    public javax.swing.JTextField popi_alamat;
    private javax.swing.JButton popi_edit;
    private javax.swing.JButton popi_hapus;
    public javax.swing.JComboBox<String> popi_jk;
    private javax.swing.JButton popi_lihat;
    private javax.swing.JButton popi_menu;
    public javax.swing.JTextField popi_nama;
    public javax.swing.JTextField popi_nim;
    public javax.swing.JTextField popi_nohp;
    private javax.swing.JButton popi_search;
    private javax.swing.JButton popi_simpan;
    // End of variables declaration//GEN-END:variables
}
