/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts.poppy.rahayu;

/**
 *
 * @author LENOVO THINKPAD X260
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        popi_mahasiswa = new javax.swing.JButton();
        popi_uangkas = new javax.swing.JButton();
        popi_logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("     MENU UTAMA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 20, 140, 48);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 51));
        jLabel2.setText("Mahasiswa");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 90, 80, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 51));
        jLabel3.setText("Uang Kas");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 90, 90, 20);

        popi_mahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uts/poppy/rahayu/icon mahasiswa.jpg"))); // NOI18N
        popi_mahasiswa.setText("jButton1");
        popi_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popi_mahasiswaActionPerformed(evt);
            }
        });
        jPanel1.add(popi_mahasiswa);
        popi_mahasiswa.setBounds(40, 110, 111, 74);

        popi_uangkas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uts/poppy/rahayu/Money_27019.png"))); // NOI18N
        popi_uangkas.setText("jButton2");
        jPanel1.add(popi_uangkas);
        popi_uangkas.setBounds(220, 110, 116, 80);

        popi_logout.setText("LOGOUT");
        jPanel1.add(popi_logout);
        popi_logout.setBounds(340, 0, 76, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO THINKPAD X260\\Documents\\NetBeansProjects\\UAS-POPPY RAHAYU\\src\\uts\\poppy\\rahayu\\login.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 420, 220);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popi_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popi_mahasiswaActionPerformed
        // TODO add your handling code here:
        new Mahasiswa().setVisible(true);
        dispose();
    }
    
    private void popi_logoutActionPerformed(java.awt.event.ActionEvent evt){
        //TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
        javax.swing.JOptionPane.showMessageDialog(null, "ANDA BERHASIL LOGOUT");
    }
     
    private void popi_uangkasActionPerformed(java.awt.event.ActionEvent evt){
        //TODO add your handling code here:
        new UangKas().setVisible(true);
        dispose();
    }//GEN-LAST:event_popi_mahasiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton popi_logout;
    private javax.swing.JButton popi_mahasiswa;
    private javax.swing.JButton popi_uangkas;
    // End of variables declaration//GEN-END:variables
}
